fail_fast: false

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        language: system
        entry: ruff check --fix
        pass_filenames: false
        types: [python]
      - id: ruff-format
        name: ruff-format
        language: system
        entry: ruff format
        pass_filenames: false
        types: [python]
      - id: ty
        name: ty
        language: system
        entry: ty check
        pass_filenames: false
        types: [python]
