"""add auto_select_single setting

Revision ID: 66a609fe9fd7
Revises: fa4d4a168ee8
Create Date: 2026-07-23 01:19:17.645174

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66a609fe9fd7"
down_revision: Union[str, Sequence[str], None] = "fa4d4a168ee8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default makes the non-null column safe to add to existing rows, backfilling
    # them to "on" (the model/default). autogenerate omits it, so it's set by hand here.
    op.add_column(
        "user_settings",
        sa.Column("auto_select_single", sa.Boolean(), nullable=False, server_default=sa.text("1")),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "auto_select_single")
    # ### end Alembic commands ###
