"""add auto_notify setting

Revision ID: 66eb12915b19
Revises: 66a609fe9fd7
Create Date: 2026-07-23 01:24:16.509785

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66eb12915b19"
down_revision: Union[str, Sequence[str], None] = "66a609fe9fd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows (auto_notify is off by default); autogenerate
    # omits it, so it's set by hand here.
    op.add_column(
        "user_settings",
        sa.Column("auto_notify", sa.Boolean(), nullable=False, server_default=sa.text("0")),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "auto_notify")
    # ### end Alembic commands ###
